export enum StateBI {
  EXPIRED = 'EXPIRED',
  BAD_CONSERVATION = 'BAD_CONSERVATION',
  ENDORSEMENT = 'ENDORSEMENT',
  LOSS = 'LOSS',
  STEALING = 'STEALING',
  NEW = 'NEW',
}

export enum SchedulingState {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  EXPIRED = 'EXPIRED',
}
